# General
namespace: python-apps
name: python-test
# Ingress
ingress:
  host: localhost
  service_port: 80
# Service
service:
  type: NodePort
  port: 80
  targetPort: 8080
# Deployment
deployment:
  replicaCount: 2
  docker_hub: kalildevops
  image: python-app
  tag: latest
  containerPort: 8080
  cpu: "0.2"
  memory: "200Mi"
# HPA
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5